### ISSUE TITLE
rsync on chocolatey - issues when enabling vscode module

### ISSUE THREAD

**Issue by gBasil** [Zerui18/XenLive-Issues-Tracker#4]
iPhone 5s - iOS 12.5.2 - XenLive v1.0.0
Windows 10

Expected Behavior:
The tweak works as intended.

Current Behavior:
When enabling the vscode module with the Chocolatey version of rsync, rsync fails to connect and gives the following error alert twice.
```
XenLive Edit: Failed to sync with device: Error: Command failed: C:\ProgramData\chocolatey\bin\rsync -rl -o --usermap="*:mobile" --delete -e 'C:\ProgramData\chocolatey\bin\ssh' //localhost/C$/Users/gunne/Documents/Programming/jailbreak/XenHTML/Eucalyptus/ 'root@192.168.0.186:/var/mobile/Library/Widgets/Universal/Eucalyptus/' rsync: Failed to exec C:\ProgramData\chocolatey\bin\ssh: No such file or directory (2) rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.2] rsync: connection unexpectedly closed (0 bytes received so far) [sender] rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
```

Steps to Reproduce:
Install the Chocolatey package manager on Windows 10
Run `choco install rsync` in an administrator powershell to install the rsync command
Add `C:\ProgramData\chocolatey\bin` to the tweak settings
Enable the module.
Check vscode alerts for the error log.

Additional:
I also tried the github actions release, which simply just said "Error: Command failed". Is this an issue with the rsync installation I am using?

**Comment by Zerui18** [comment]
Hi, thanks for trying out XenLive.

Due to the inconveniences of setting up and maintaining rsync, as well as performance considerations, XenLive v1.1.0 is being developed and it's using a custom solution built from ground up for fast syncing. It's currently in public beta testing, if you're interested in pilot testing it, you can join our discord server here: https://discord.gg/Fx2Fy9rr and under the channel "Public Development > xen_live_beta"!

**Comment by GunnerBasil** [comment]
Sure thing!
